version: 0.2

env:
  variables:
    DOCKER_IMAGE_NAME: next-starter
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    AWS_REGION: eu-central-1
    EC2_INSTANCE_PUBLIC_IP: ubuntu@ec2-35-158-26-108.eu-central-1.compute.amazonaws.com
    EC2_SSH_KEY: ${{secrets.EC2_SSH_KEY}} 
    DOCKER_IMAGE_TAG: latest
    $AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    $AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install AWS CLI if it's not installed already
      - echo Installing AWS CLI
      - pip install --upgrade awscli
      - echo "Fetching secrets from AWS Secrets Manager..."
      - export MY_SECRET_KEY=$(aws secretsmanager get-secret-value --secret-id /myproject/github_token --query SecretString --output text | jq -r '.MY_SECRET_KEY')

  pre_build:
    commands:
      # Log into Docker Hub
      - echo Logging into Docker Hub
      - docker login -u vukankoprivica35 -p $DOCKER_PASSWORD
      
      # Authenticate AWS CLI using IAM credentials (from GitHub Secrets or AWS environment)
      - echo Configuring AWS credentials
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - export AWS_DEFAULT_REGION=$AWS_REGION
      
  build:
    commands:
      # Build the Docker image
      - echo Building Docker image
      - docker build -t vukankoprivica35/next-starter:latest .
      # Push the Docker image to Docker Hub
      - echo Pushing Docker image to Docker Hub
      - sudo docker push docker.io/vukankoprivica35/next-starter:latest 


artifacts:
  files:
    - '**/*'
  discard-paths: yes
