version: 0.2

env:
  variables:
    DOCKER_IMAGE_NAME: next-starter
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    AWS_REGION: us-east-1
    EC2_INSTANCE_PUBLIC_IP: ubuntu@ec2-35-158-26-108.eu-central-1.compute.amazonaws.com
    EC2_SSH_KEY: ${{secrets.EC2_SSH_KEY}} 
    DOCKER_IMAGE_TAG: latest
    $AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    $AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install AWS CLI if it's not installed already
      - echo Installing AWS CLI
      - pip install --upgrade awscli
      - echo "Fetching secrets from AWS Secrets Manager..."
      - export MY_SECRET_KEY=$(aws secretsmanager get-secret-value --secret-id /myproject/github_token --query SecretString --output text | jq -r '.MY_SECRET_KEY')

  pre_build:
    commands:
      # Log into Docker Hub
      - echo Logging into Docker Hub
      - docker login -u vukankoprivica35 -p Durantula35@
      
      # Authenticate AWS CLI using IAM credentials (from GitHub Secrets or AWS environment)
      - echo Configuring AWS credentials
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - export AWS_DEFAULT_REGION=$AWS_REGION
      
  build:
    commands:
      # Build the Docker image
      - echo Building Docker image
      - docker build -t vukankoprivica35/next-starter:latest .

      - docker images

      - docker tag vukankoprivica35/next-starter  vukankoprivica35/next-starter:latest

      # Push the Docker image to Docker Hub
      - echo Pushing Docker image to Docker Hub
      - sudo docker push docker.io/vukankoprivica35/next-starter:latest 

  post_build:
   commands:
      # Set up the SSH private key from GitHub secrets
      - echo Setting up SSH key for EC2 access
      - echo $MY_SECRET_KEY > ec2-key.pem
      - chmod 400 ec2-key.pem
      - eval "$(ssh-agent -s)"
      - echo "$MY_SECRET_KEY" | ssh-add -
      - ls -l ec2-key.pem # Check if file was created
      - file ec2-key.pem
      - cat ec2-key.pem
      - ssh-add ec2-key.pem
      - ssh-keygen -p -f ec2-key.pem -m PEM

      # SSH into EC2 and run the Docker container
      - echo SSHing into EC2 instance and running Docker container
      - ssh -v -i ec2-key.pem -T -o StrictHostKeyChecking=no ubuntu@ec2-35-158-26-108.eu-central-1.compute.amazonaws.com <<EOF
          sudo docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
          sudo docker stop $(sudo docker ps -q --filter "ancestor=$DOCKER_USERNAME/$DOCKER_IMAGE_NAME")
          sudo docker run -d -p 3000:3000 $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
        EOF


artifacts:
  files:
    - '**/*'
  discard-paths: yes
