version: 0.2

env:
  variables:
    DOCKER_IMAGE_NAME: next-starter
    DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    AWS_REGION: us-east-1
    EC2_INSTANCE_PUBLIC_IP: ubuntu@ec2-35-158-26-108.eu-central-1.compute.amazonaws.com
    EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }} 
    DOCKER_IMAGE_TAG: latest
    $AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    $AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install AWS CLI if it's not installed already
      - echo Installing AWS CLI
      - pip install --upgrade awscli

  pre_build:
    commands:
      # Log into Docker Hub
      - echo Logging into Docker Hub
      - echo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
      
      # Authenticate AWS CLI using IAM credentials (from GitHub Secrets or AWS environment)
      - echo Configuring AWS credentials
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - export AWS_DEFAULT_REGION=$AWS_REGION
      
  build:
    commands:
      # Build the Docker image
      - echo Building Docker image
      - docker build -t vukankoprivica35/next-starter:latest .

      - docker images
      
      - docker tag next-starter:latest vukankoprivica35/next-starter:latest

      # Push the Docker image to Docker Hub
      - echo Pushing Docker image to Docker Hub
      - sudo docker push vukankoprivica35/next-starter:latest 

  post_build:
   commands:
      # Set up the SSH private key from GitHub secrets
      - echo Setting up SSH key for EC2 access
      - touch ec2-key.pem
      - echo $EC2_SSH_KEY > ec2-key.pem
      - chmod 400 ec2-key.pem
      - ssh-keyscan -H ubuntu@ec2-35-158-26-108.eu-central-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      # SSH into EC2 and run the Docker container
      - echo SSHing into EC2 instance and running Docker container
      - ssh -v -i ec2-key.pem -T ubuntu@ec2-35-158-26-108.eu-central-1.compute.amazonaws.com <<EOF
          sudo docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
          sudo docker stop $(sudo docker ps -q --filter "ancestor=$DOCKER_USERNAME/$DOCKER_IMAGE_NAME")
          sudo docker run -d -p 3000:3000 $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
        EOF


artifacts:
  files:
    - '**/*'
  discard-paths: yes
