name: Deploy next-starter application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Build docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/next-starter .
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Publisch image to docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/next-starter:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Pull image from Docker Hub
      run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/next-starter:latest
    - name: Delete old container
      run: sudo docker rm -f next-starter-container
    - name: Run docker container
      run: sudo docker run -d -p 3000:3000 --name next-starter-container ${{ secrets.DOCKER_USERNAME }}/next-starter:latest
  
